<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Customers.aspx.cs" Inherits="GoodFood.Customers" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <%-- titile --%>
    <div class="row">
        <div class="col-md-4">
            <span style="font-size: xx-large; font-weight: 700;">Customer Table</span>
        </div>
    </div>

    <%-- sub title --%>
    <div class="row">
        <div class="col-md-4">
            <span style="font-size: medium">View, update and delete customer details</span>
        </div>
    </div>
    <br />

    <%-- customer name --%>
    <div class="row">
        <div class="col-md-4">
            <asp:Label ID="Label1" runat="server" Text="Customer Name"></asp:Label>
        </div>
    </div>

    <%-- customer name text field --%>
    <div class="row">
        <div class="col-md-4">
            <asp:TextBox class="textbox" ID="nameTxt" runat="server" BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="25px"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="name cannot be empty" ControlToValidate="nameTxt" Font-Size="X-Small" ForeColor="Red" style="font-size: smaller" ValidationGroup="customerGroup"></asp:RequiredFieldValidator>
        </div>
    </div>

    <%-- expression validation --%>
    <div class="row">
        <div class="col-md-4">
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ErrorMessage="invalid input" ControlToValidate="nameTxt" ForeColor="Red" style="font-size: smaller" ValidationGroup="customerTable" ValidationExpression="^([a-zA-Z]+\s*)+$"></asp:RegularExpressionValidator>
        </div>
    </div>


      <%-- customer address --%> 
    <div class="row">
        <div class="col-md-4">
            <asp:Label ID="Label2" runat="server" Text="Customer Address"></asp:Label>
        </div>
    </div>


    <%-- customer address text field --%>
    <div class="row">
        <div class="col-md-4">  
            <asp:TextBox class="textbox" ID="addressTxt" runat="server" BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="25px"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="address cannot be empty" ControlToValidate="addressTxt" ForeColor="Red" style="font-size: smaller" ValidationGroup="customerGroup"></asp:RequiredFieldValidator>
        </div>
    </div>


    <%-- expression validation --%>
    <div class="row">
        <div class="col-md-4">
            <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" ErrorMessage="invalid input" ValidationExpression="^([a-zA-Z]+\s*)+$" ControlToValidate="addressTxt" ForeColor="Red" style="font-size: smaller" ValidationGroup="customerGroup"></asp:RegularExpressionValidator>
        </div>
    </div>


    <%-- customer phone --%>
    <div class="row">
        <div class="col-md-4">
            <asp:Label ID="Label3" runat="server" Text="Customer Phone"></asp:Label>
        </div>
    </div>


    <%-- customer form text field --%>
    <div class="row">
        <div class="col-md-4">  
            <asp:TextBox class="textbox" ID="phoneTxt" runat="server" BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="25px"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="contact cannot be empty" ForeColor="Red" style="font-size: smaller" ControlToValidate="phoneTxt" ValidationGroup="customerGroup"></asp:RequiredFieldValidator>
        </div>
    </div>


    <%-- expression validation --%>
    <div class="row">
        <div class="col-md-4">
            <asp:RegularExpressionValidator ID="RegularExpressionValidator3" runat="server" ErrorMessage="invalid input" ControlToValidate="phoneTxt" ForeColor="Red" style="font-size: smaller" ValidationGroup="customerGroup" ValidationExpression="^[0-9]{10}$"></asp:RegularExpressionValidator>
        </div>
    </div>

    
    <%-- insert button --%>
    <div class="row">
        <div class="col-md-4">
            <asp:Button class="button" ID="insertBtn" runat="server" Text="Insert" OnClick="insertBtn_Click" BackColor="#1877F2" BorderColor="#1877F2" BorderStyle="None" ForeColor="White" ValidationGroup="customerGroup" />
        </div>
    </div>
    <br />

    <%-- grid view --%>
    <div class="row">
        <div class="col-md-4">
            <asp:GridView cellpadding="8" ID="GridViewCustomer" runat="server" DataKeyNames="Customer_id" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" Font-Size="Medium" Width="1094px" BorderColor="#CCCCCC" BorderStyle="Solid">
            </asp:GridView>
        </div>
    </div>
 </asp:Content>
